.circleci/config.yml, docs/Makefile, docs/README.md, docs/conf.py, docs/development.md, docs/index.md, docs/using.md, setup.py
This adds some documentation with Sphinx - it re-purposes the pre-existing docs for this. It also re-uses the `README.md` file for the main repository as the `index.md` for the docs, though we can always change that around later if we wish.
What do you think @chrisjsewell ? If you're +1 then I'll also add this to RTD
=> adding documentation

markdown_it/extensions/amsmath/__init__.py, tests/test_amsmath/fixtures.md, tests/test_amsmath/test_amsmath.py, tests/test_amsmath/test_amsmath/test_plugin_parse.yml
Adds extension to specifically capture top-level [amsmath](https://ctan.org/pkg/amsmath?lang=en) latex environments
cc @choldgraf @phaustin for comment
=> add amsmath extension

markdown_it/rules_block/list.py
This is a minimal fix for #31 
Here's a copy/paste of things discussed in the issue for reference:
When processing lists, there is a call to tokenize() that advances the state.line attribute :
list.py 
line 264: state.md.block.tokenize(state, startLine, endLine)
After this line is executed, state.line can be larger than endLine, leading to the IndexError when checking the state at that index.
Breaking right after this line if state.line > endLine doesn't work though, we have to update the `nextline` variable before, as well as closing the list. It's actually already in the codebase, but one line too late:
line 280 onwards:
token = state.push("list_item_close", "li", -1)
token.markup = chr(markerCharCode)
nextLine = startLine = state.line
itemLines[1] = nextLine
contentStart = …
=> 🐛 FIX: empty lines after certain lists raises exception

.pre-commit-config.yaml
- Use upstream flake8 pre-commit hook (see https://github.com/pre-commit/pre-commit-hooks#deprecated--replaced-hooks)
- Run `pre-commit autoupdate`
=> Pre-commit improvements

markdown_it/utils.py
Currently `read_fixture_file` decides file encoding based on platform. It may read different text from the same file when running on a different platform (Windows, linux, macOS etc.), and as a result, break tests on some platforms (typically windows, lol).
This PR makes the function read UTF-8 regardless of platform.
=> 🧪 Make `read_fixture_file` always read UTF-8

markdown_it/rules_block/state_block.py, tests/test_port/fixtures/issue-fixes.md, tox.ini
=> 🐛 FIX: blank lines after block quotes

markdown_it/main.py, tests/test_api/test_main.py
This PR makes `MarkdownIt.render` not copy an `env` if it is an empty `AttrDict`, making it possible for a caller to capture changes made to `env`. This is in line with how `MarkdownIt.parse` method, and the JS implementation works.
=> 🐛 FIX: `MarkdownIt.render`; don't copy empty `env` arg

markdown_it/common/utils.py, markdown_it/rules_core/smartquotes.py
This bug was found by running mypy with the [`strict_equality = True`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict-equality) setting. I suggest we turn that setting on in https://github.com/executablebooks/markdown-it-py/pull/64
=> 🐛 FIX: smartquotes punctuation char comparison

markdown_it/common/utils.py, tests/test_port/fixtures/issue-fixes.md
Closes https://github.com/executablebooks/markdown-it-py/issues/80
This seems like a porting issue to me: Javascript needs two string characters for codepoints larger than `0xFFFF` but Python 3 can represent any unicode codepoint in one character.
This PR removes the handling that splits a large codepoint to two chars.
=> 🐛 FIX: parsing of unicode ordinals

markdown_it/rules_block/blockquote.py, markdown_it/rules_block/heading.py, tests/test_port/test_no_end_newline.py
Closes https://github.com/executablebooks/markdown-it-py/issues/71
=> 🐛 FIX: Exception when doc ends in heading/blockquote marker

.mypy.ini, .pre-commit-config.yaml, MANIFEST.in, markdown_it/common/entities.py, markdown_it/common/normalize_url.py, markdown_it/common/utils.py, markdown_it/extensions/anchors/index.py, markdown_it/extensions/container/index.py, markdown_it/extensions/deflist/index.py, markdown_it/extensions/footnote/index.py, markdown_it/extensions/tasklists/__init__.py, markdown_it/main.py, markdown_it/parser_block.py, markdown_it/renderer.py, markdown_it/ruler.py, markdown_it/rules_block/blockquote.py, markdown_it/rules_block/heading.py, markdown_it/rules_block/html_block.py, markdown_it/rules_block/state_block.py, markdown_it/rules_core/replacements.py, markdown_it/rules_core/smartquotes.py, markdown_it/rules_inline/autolink.py, markdown_it/rules_inline/balance_pairs.py, markdown_it/rules_inline/image.py, markdown_it/rules_inline/state_inline.py, markdown_it/rules_inline/strikethrough.py, markdown_it/token.py, markdown_it/utils.py
Closes https://github.com/executablebooks/markdown-it-py/issues/19
=> 🔧 MAINTAIN: Add mypy type-checking

markdown_it/main.py
=> 📚 DOCS: Fix docstring

markdown_it/renderer.py
The token stream should not be mutated while rendering (https://github.com/markdown-it/markdown-it/issues/260).
This PR type annotates token stream as the immutable `Sequence` to make type checkers check for possible mutation.
=> 👌 IMPROVE: Type annotate renderer's token stream immutable

tests/test_port/test_fixtures.py
Nothing to do with #8
`typographer` was enabled in the [js version](https://github.com/markdown-it/markdown-it/blob/master/test/markdown-it.js#L14). 
`---` will be converted to a `—`(&mdash).
=> 🧪 TEST: Enable typographer to fix skipped

markdown_it/parser_block.py, markdown_it/ruler.py, markdown_it/rules_block/state_block.py
`StateBase.srcCharCode` is tightly coupled with `StateBase.src` value so should not be mutated, only reassigned atomically with `StateBase.src`. This PR makes it immutable. Also prevent initializing `srcCharCode` value twice in `StateBase` init.
=> 👌 IMPROVE: Make `srcCharCode` immutable

markdown_it/main.py, markdown_it/port.yaml, markdown_it/rules_block/blockquote.py, markdown_it/rules_block/table.py, markdown_it/rules_inline/balance_pairs.py, tests/test_port/fixtures/commonmark_extras.md
Implement the diff https://github.com/markdown-it/markdown-it/compare/f798bea9623277bbf89b9621cf7fb283c693fcab...331ae117e09115366db12b517ca526b1b7fee1e8 to catch up with the JS project a bit.
=> 🐛 FIX: port markdown-it v11.0.1

markdown_it/cli/parse.py, tests/test_cli.py
Based on @westurner's https://github.com/executablebooks/markdown-it-py/pull/55 with two changes:
- Fix CI
- Fix error code when running `python markdown_it/cli/parse.py`
=> 🐛 FIX: cli.parse: return 0 for non-error

markdown_it/token.py
It seems `NestedTokens` represents a `_open` token and `_close` token pair and the tokens in the stream between them. I think closing token should not be optional?
=> 👌 IMPROVE: Make `NestedTokens.closing` not optional

markdown_it/token.py, markdown_it/tree.py, markdown_it/utils.py, tests/test_syntax_tree_node.py, tests/test_tree.py
Context: read the thread here https://github.com/executablebooks/mdformat/pull/132#discussion_r582360434
=> ✨ NEW: Add SyntaxTreeNode

markdown_it/tree.py
Realized I can not subclass and add methods to the tree class, because it always instantiates the base class. This fixes it
=> 👌 IMPROVE: Make `SyntaxTreeNode` subclassable

markdown_it/common/normalize_url.py, markdown_it/main.py, markdown_it/port.yaml, markdown_it/rules_block/reference.py, markdown_it/rules_block/state_block.py, markdown_it/rules_core/linkify.py, markdown_it/rules_inline/autolink.py, markdown_it/rules_inline/image.py, markdown_it/rules_inline/link.py
`validateLink`,  `normalizeLink` and `normalizeLinkText` are now methods of `MarkdownIt`,
meaning that they can be overriden by subclassing `MarkdownIt`.
=> 👌 IMPROVE: Make link functions overridable

.pre-commit-config.yaml, .readthedocs.yml, docs/conf.py, docs/using.md, markdown_it/main.py, markdown_it/port.yaml, markdown_it/presets/__init__.py, markdown_it/presets/commonmark.py, markdown_it/renderer.py, markdown_it/tree.py, tests/test_api/test_main.py, tests/test_tree.py, tests/test_tree/test_pretty.xml, tox.ini
Add additional configuration presets,
allow for options tp be overriden in the `MarkdownIt` initialisation,
Add convenience methods to `SyntaxTreeNode`
=> 👌 IMPROVE: MarkdownIt config and documentation

markdown_it/rules_core/linkify.py, tests/test_linkify.py
It seems to me like linkify link tokens have incorrect nesting levels. This PR fixes that.
~~This seems like a bug inherited from upstream. I'll make a quick PR there as well.~~ EDIT: On closer inspection this seems like a porting issue, so not making an upstream PR.
=> 🐛 FIX: Linkify link nesting levels

tests/test_port/test_fixtures.py
context: https://docs.pytest.org/en/documentation-restructure/how-to/skipping.html
I think `xfail` is more correct than `skip` for these tests.
=> 🧪 TESTS: Use pytest.xfail not pytest.skip

markdown_it/tree.py, tests/test_tree.py
Add a method for SyntaxTreeNode traversal.
Would be useful e.g. here https://github.com/executablebooks/mdformat-tables/pull/7/files
=> ✨ NEW: Add SyntaxTreeNode.walk

markdown_it/main.py, markdown_it/port.yaml, markdown_it/presets/commonmark.py, markdown_it/presets/default.py, markdown_it/presets/zero.py, markdown_it/renderer.py, markdown_it/ruler.py, markdown_it/rules_block/reference.py, markdown_it/rules_core/state_core.py, markdown_it/rules_inline/image.py, markdown_it/rules_inline/link.py, markdown_it/rules_inline/state_inline.py, markdown_it/utils.py, tests/test_api/test_main.py, tests/test_port/test_references.py
For `env` any Python mutable mapping is now allowed,
and so attribute access to keys is not allowed.
For `MarkdownIt.options` it is now set as an `OptionsDict`,
which is a dictionary sub-class, with attribute access
only for core markdownit configuration keys.
=> ‼️ BREAKING: Replace use of `AttrDict` for env/options

markdown_it/port.yaml, markdown_it/rules_block/table.py, markdown_it/token.py, tests/test_port/fixtures/tables.md
This is a port of the latest upstream changes. See the description in https://github.com/markdown-it/markdown-it/pull/767
=> 🐛 FIX: List/table parsing ambiguity

README.md
Hello,
I was playing with this package and noticed that there are a couple of warning messages with the current important commands. 
Also one other suggestion is to add some code for people to export the html to a file if they happen to not be working in an interactive python session. Happy to remove this if it doesn't make sense for others.
=> 📚 DOCS: Fix deprecated import

markdown_it/parser_block.py, markdown_it/port.yaml, tests/test_api/test_main.py, tests/test_port/fixtures/commonmark_extras.md
Sibling PR to upstream commit https://github.com/markdown-it/markdown-it/commit/309c03a9e856ad5f39ea5e7c066198a93b9331fb
=> 🐛 FIX: Raise HTML blocks priority to resolve conflict with headings

markdown_it/port.yaml, markdown_it/renderer.py, tests/test_port/fixtures/commonmark_extras.md
This is a sibling of the upstream PR https://github.com/markdown-it/markdown-it/pull/775
=> 🐛 FIX: Newline not rendered in image alt attribute

.pre-commit-config.yaml, docs/conf.py, setup.cfg
The name of the package is already set up to use `markdown-it-py` in numerous places, but setup_cfg_fmt is hard-coded to convert these dashes to underscores https://github.com/asottile/setup-cfg-fmt/blob/de922db829605a067c7a407eb42620c3cb4466a0/setup_cfg_fmt.py#L365 🤷
=> 🔧 MAINTAIN: Update development packages

CHANGELOG.md, markdown_it/__init__.py
Note 1.0.0b3 has already been tested against:
- https://github.com/executablebooks/MyST-Parser/pull/355
- https://github.com/executablebooks/MyST-NB/pull/320
- https://github.com/mwouts/jupytext/pull/769
- https://github.com/executablebooks/mdformat/pull/207
so 🤞 this should be a smooth rollout
=> 🚀 RELEASE: v1.0.0

docs/conf.py, docs/plugins.md
Moved to https://mdit-py-plugins.readthedocs.io
=> 📚 DOCS: Move plugin documentation

markdown_it/port.yaml, markdown_it/rules_block/code.py, tests/test_port/test_no_end_newline.py
I'll propose this change upstream and add a link here soon. Probably don't want to merge before accepted upstream.
EDIT: Here's the upstream PR https://github.com/markdown-it/markdown-it/pull/799
=> 🐛 FIX: Always suffix indented code block with newline

.github/workflows/tests.yml
it's deprecated https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> 🔧 MAINTAIN: Use `pyproject-build` for package deployment

markdown_it/common/entities.py, markdown_it/common/utils.py, markdown_it/rules_block/list.py, markdown_it/rules_inline/entity.py, markdown_it/utils.py, setup.cfg
This is no longer used is core or mdit-py-plugins,
instead standard dictionaries are used.
=> ♻️ REFACTOR: Remove `AttrDict`

markdown_it/rules_block/blockquote.py, tests/test_port/test_no_end_newline.py
Closes https://github.com/executablebooks/markdown-it-py/issues/185
=> 🐛 FIX: Crash when file ends with empty blockquote line

MANIFEST.in, profiler.py, setup.cfg, tox.ini
Now that mistletoe [beat us](https://github.com/executablebooks/markdown-it-py/pull/196/files) (congrats to them!) I was curious to see if there's any easy ways to improve our performance and regain the number one spot :smile: I came up with a profiler tox env and thought you may want to merge it to the repository?
=> 🔧 MAINTAIN: Add a profiler tox env

markdown_it/port.yaml, markdown_it/rules_block/list.py, markdown_it/token.py, tests/test_port/test_misc.py
A port of this diff https://github.com/markdown-it/markdown-it/compare/e5986bb7cca20ac95dc81e4741c08949bf01bb77...12.2.0
=> ✨ NEW: Save ordered list numbering

tests/test_port/fixtures/commonmark_extras.md
Test case for [executablebooks/markdown-it-py:205](https://github.com/executablebooks/markdown-it-py/issues/205)
This test will be fixed by https://github.com/executablebooks/mdurl/pull/7
=> 🧪 TEST: Space in link destination generates `IndexError`

docs/_static/custom.css, docs/architecture.md, docs/conf.py, pyproject.toml, tox.ini
By temporarily removing myst-nb
=> 📚 DOCS: Fix build

markdown_it/ruler.py, markdown_it/rules_inline/state_inline.py
In order to remove attr dependency
=> ♻️ REFACTOR: Move internal `Rule`/`Delimiter` to dataclass

markdown_it/token.py, pyproject.toml
In order to remove `attrs` dependency.
=> ♻️ REFACTOR: Move `Token` to `dataclass`

CHANGELOG.md, markdown_it/__init__.py
@hukkin do you have any objections, regarding releasing this as 2.1 rather than 3.0?
Fo 99% of use cases, I don't think there should be a noticeable change, moving from attrs to dataclasses (it certainly did not affect myst-parser)
=> 🚀 RELEASE: v2.1.0

docs/using.md
Inspired by [this](https://github.com/executablebooks/markdown-it-py/issues/10#issuecomment-1168524116) message in #10
=> 📚 DOCS: Add section about markdown renderer

pyproject.toml
A port of linkify-it 4.0.0 ([changelog here](https://github.com/markdown-it/linkify-it/blob/master/CHANGELOG.md#400--2022-04-22)) which makes a couple fixes and adds a new method
=> ⬆️ UPGRADE: Allow linkify-it-py v2

README.md
It is a very bad idea to `.disable('image')` in the example , most newbies just copy the example to test, by  `.disable('image')` causes unnecessary problem for them. I suffered the problem. So let's make a more user-friendly example.
=> 📚 DOCS: Update the example

markdown_it/cli/parse.py, tests/test_cli.py
=> 🐛 FIX: CLI crash on non-utf8 character

markdown_it/rules_block/blockquote.py, markdown_it/rules_block/fence.py, markdown_it/rules_block/hr.py, markdown_it/rules_block/list.py, tests/test_fuzzer.py
From https://github.com/google/oss-fuzz/tree/master/projects/markdown-it-py,
fixes issues 55363 and 55367
=> 🧪 Fix fuzzing test failures

.github/workflows/fuzz.yml, .github/workflows/tests.yml
This action runs fuzzing for a brief period of time, only against the actual code added in the PR.
It is intended as a relatively quick check,
to guard against code introducing crashes in the Markdown parsing, which should in principle always run against any text input. See: https://google.github.io/oss-fuzz/getting-started/continuous-integration/#how-it-works
=> 🧪 CI: Add fuzzing workflow for PRs

.github/workflows/tests.yml, .readthedocs.yml, docs/conf.py, markdown_it/renderer.py, pyproject.toml, tox.ini
Python 3.7 is end-of-life on 2023-06-27 https://devguide.python.org/versions/
=> ⬆️ Drop Python 3.7

markdown_it/rules_block/blockquote.py, markdown_it/rules_block/code.py, markdown_it/rules_block/fence.py, markdown_it/rules_block/heading.py, markdown_it/rules_block/hr.py, markdown_it/rules_block/html_block.py, markdown_it/rules_block/lheading.py, markdown_it/rules_block/list.py, markdown_it/rules_block/reference.py, markdown_it/rules_block/state_block.py, markdown_it/rules_block/table.py, tests/test_port/fixtures/disable_code_block.md, tests/test_port/test_fixtures.py
For CommonMark, the presence of indented code blocks prevent any other block element from having an indent of greater than 4 spaces.
Certain Markdown flavors and derivatives, such as mdx and djot, disable these code blocks though, since it is more common to use code fences and/or arbitrary indenting is desirable.
Currently, disabling code blocks does not remove the indent limitation, since most block elements have the 3 space limitation hard-coded.
This commit therefore centralises the logic of applying this limitation, and only applies it when indented code blocks are enabled.
Note, this is a potential breaking change and divergence from upstream markdown-it, for this niche case, but I feel makes sense and could even be upstreamed.
=> 👌 Centralise indented code block test

markdown_it/common/utils.py, tests/test_fuzzer.py, tests/test_port/fixtures/issue-fixes.md
Fix issue with incorrect determination of a numeric character reference, and subsequent failure to convert to an integer code.
From https://github.com/google/oss-fuzz/tree/master/projects/markdown-it-py, fixes issue 55371
This also essentially fixes a bug in upstream, see https://github.com/markdown-it/markdown-it/issues/935
=> 🐛 FIX: numeric character reference passing

markdown_it/port.yaml, markdown_it/rules_inline/balance_pairs.py, markdown_it/rules_inline/emphasis.py, markdown_it/rules_inline/state_inline.py, markdown_it/rules_inline/strikethrough.py
This fixes quadratic complexity in e.g. `**<...>**a**<...>**`
Implementation of upstream commit: https://github.com/markdown-it/markdown-it/commit/24abaa51a605c2de14da59893797733921f09bb8
=> 👌 Improve nested emphasis parsing

markdown_it/port.yaml, markdown_it/rules_block/list.py, tests/test_port/fixtures/commonmark_extras.md
Implements upstream: https://github.com/markdown-it/markdown-it/commit/1cd8a5143b22967a7583bba19678900efdf72adf
=> 🐛 Fix: tab preventing paragraph continuation in lists

markdown_it/port.yaml, markdown_it/rules_inline/newline.py
Implements upstream: https://github.com/markdown-it/markdown-it/commit/ffc49ab46b5b751cd2be0aabb146f2ef84986101
=> 👌 fix possible ReDOS in newline rule

markdown_it/parser_core.py, markdown_it/parser_inline.py, markdown_it/presets/commonmark.py, markdown_it/presets/zero.py, markdown_it/rules_core/__init__.py, markdown_it/rules_core/text_join.py, markdown_it/rules_inline/__init__.py, markdown_it/rules_inline/escape.py, markdown_it/rules_inline/fragments_join.py, tests/test_api/test_main.py, tests/test_port/fixtures/linkify.md, tests/test_port/fixtures/smartquotes.md, tests/test_port/fixtures/typographer.md
Smartquotes, typographic replacements and plain text links can now be escaped with backslash (e.g. `\(c)` or `google\.com` are no longer replaced).
Implements upstream: https://github.com/markdown-it/markdown-it/commit/75037c6514e99c9b4fa300f62f04913fee4ea0e2
Breaking:
- `text_collapse` rule is renamed to `fragments_join`
- Added a new token type `text_special` to store escaped characters, same as `text` but unaffected by replacement plugins (smartquotes, typographer, linkifier, etc.).
- Added a new rule `text_join` in `core` ruler. Text replacement plugins may choose to insert themselves before it.
=> ♻️ Refactor backslash escape logic

markdown_it/common/utils.py, markdown_it/parser_inline.py, markdown_it/presets/__init__.py, markdown_it/rules_core/linkify.py, markdown_it/rules_inline/__init__.py, markdown_it/rules_inline/html_inline.py, markdown_it/rules_inline/link.py, markdown_it/rules_inline/linkify.py, markdown_it/rules_inline/state_inline.py, tests/test_api/test_main.py, tests/test_port/fixtures/linkify.md
Fixes collision of emphasis and linkifier (so `http://example.org/foo._bar_-_baz`
is now a single link, not emphasized). Emails and fuzzy links are not affected by this.
Implements upstream: https://github.com/markdown-it/markdown-it/commit/6b58ec4245abe2e293c79bd7daabf4543ef46399
=> ♻️ Refactor: Add linkifier rule to inline chain for full links

markdown_it/rules_inline/entity.py, tests/test_port/fixtures/smartquotes.md, tests/test_port/fixtures/typographer.md
Rather than adding directly to text.
The `text_join` core rule then joins it to the text later, but after typographic rules have been applied.
Implements upstream: https://github.com/markdown-it/markdown-it/commita/3fc0deb38b5a8b2eb8f46c727cc4e299e5ae5f9c
=> ♻️ Parse entities to `text_special` token

markdown_it/port.yaml, markdown_it/rules_core/replacements.py, tests/test_port/fixtures/typographer.md
`(p)` is no longer replaced with § by typographer (conflicts with ℗)
Implements upstream: https://github.com/markdown-it/markdown-it/commit/f52351499be1e6c838110c31e07154cce1d91d47
=> ‼️ Remove (p) => § replacement in typographer

markdown_it/tree.py, tests/test_tree.py, tests/test_tree/test_pretty_text_special.xml
Provides a demonstration of how the new `text_special` token parsing works
=> 👌 Show text of `text_special` in `tree.pretty`

docs/conf.py, markdown_it/parser_block.py, markdown_it/parser_core.py, markdown_it/parser_inline.py, markdown_it/ruler.py, markdown_it/rules_block/lheading.py, markdown_it/rules_block/paragraph.py, tests/test_api/test_plugin_creation.py
Rule functions signature is specific to the state it acts on.
=> 🔧 Add typing of rule functions

README.md
=> 📚 Fix CI badge link

README.md, docs/index.md, docs/security.md
=> 📚 DOCS: Clarify docs regarding security configuration

markdown_it/rules_inline/linkify.py, tests/test_port/fixtures/linkify.md
Fix #300 
Changed from `re.match` to `re.search` to work as intended.
=> 🐛 Fix emphasis inside raw links bugs

.github/workflows/benchmark.yml, .github/workflows/tests.yml, .readthedocs.yml, docs/conf.py, docs/contributing.md, markdown_it/common/utils.py, markdown_it/utils.py, pyproject.toml, tox.ini
Python 3.9 is end-of-life as of 2024-10-07 (https://devguide.python.org/versions/)
=> ⬆️ Drop Python 3.9, test 3.13

.gitignore, .pre-commit-config.yaml, docs/conf.py, docs/contributing.md, markdown_it/utils.py, pyproject.toml
=> 🔧 Add "store_labels" to OptionsType

markdown_it/rules_inline/text.py
This slightly deviates from JavaScript, but improves performance a lot.
Below the before/after results from `tox -e py312-bench-core`.
Before:
```
------------------------------------------ benchmark 'core': 1 tests ------------------------------------------
Name (time in ms)         Min      Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------
test_spec             80.6105  90.4756  83.9440  4.1692  81.2779  7.7111       4;0  11.9127      12           1
---------------------------------------------------------------------------------------------------------------
```
After:
```
------------------------------------------ benchmark 'core': 1 tests …
```
=> 👌 Improve performance of "text" inline rule

.readthedocs.yml, docs/contributing.md
Add required configuration to `.readthedocs.yaml`. See <https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/>.
Correct a few links in the documentation:
1. Correct the EBP Contributing Guide link
2. Correct links to markdown-it source code (extensions changed from `.js` to `.mjs`; this relates to https://github.com/markdown-it/markdown-it/pull/981)
=> 📚 DOCS: Fix a few old URLs

.github/workflows/benchmark.yml, .github/workflows/tests.yml, .readthedocs.yml, docs/conf.py, docs/contributing.md, markdown_it/_compat.py, markdown_it/_punycode.py, markdown_it/parser_block.py, markdown_it/parser_core.py, markdown_it/parser_inline.py, markdown_it/ruler.py, markdown_it/rules_inline/state_inline.py, markdown_it/token.py, markdown_it/utils.py, pyproject.toml, tox.ini
This is EoL next month https://devguide.python.org/versions
=>  ⬆️ Drop support for Python 3.9

markdown_it/rules_inline/state_inline.py
ports https://github.com/markdown-it/markdown-it/commit/5e900639542bb36501ee9e960c07bfaa529431c9
=> 🔧 simplify logic in scanDelims

docs/architecture.md, docs/security.md
I've taken the liberty of correcting a few typos and adding a few definite articles ("the") to the documentation.
=> 📚 DOCS: Fix typos
